language: cpp
os: linux
dist: trusty

matrix:
  include:
  - addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
        - libogre-1.9-dev
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7" PYTHON_VERSION=3.6


before_install:
- pyenv global system $PYTHON_VERSION
- eval "${MATRIX_EVAL}"

before_script:
- mkdir build && cd build
- cmake .. -DPYBIND11_PYTHON_VERSION=$PYTHON_VERSION

script:
- cmake --version
- ${CC} --version
- ${CXX} --version
- make VERBOSE=1 && ctest .
