language: cpp

addons:
  apt:
    packages:
    - python3.6
    - python3.6-dev

compiler:
- gcc
- clang

before_script:
- mkdir build
- cd build
- cmake .. -DPYBIND11_PYTHON_VERSION=3.6

script:
- cmake --build
- ctest .
