language: cpp

matrix:
  include:
  - os: linux
    dist: trusty
    compiler: clang
    env:
    - PYTHON_VERSION=3.6
    addons:
      apt:
        packages:
        - libogre-1.9-dev

before_install:
- pyenv global system $PYTHON_VERSION
- pip install --user --upgrade pip virtualenv
- virtualenv -p python$PYTHON_VERSION venv
- source venv/bin/activate

before_script:
- mkdir build
- cd build
- cmake .. -DPYBIND11_PYTHON_VERSION=$PYTHON_VERSION

script:
- cmake --build .
- ctest .
